export declare const colorDark: string
export declare const colorLite: string
export declare const colorMedium: string
export declare const commitCalendar: string
export declare const dayCell: string
export declare const daysGrid: string
export declare const line: string
export declare const monthColumn: string
export declare const monthName: string
export declare const repoAvatar: string
export declare const repoBranchesList: string
export declare const repoContributions: string
export declare const repoContributors: string
export declare const repoContributorsList: string
export declare const repoCounter: string
export declare const repoCounters: string
export declare const repoInfo: string
export declare const repoInfoBlock: string
export declare const repoInfoRoot: string
export declare const repoOwner: string
